[project]
name = "esr"
version = "0.2.0"
description = "Small project to pull and collate CAISO's ESR"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.2",
    "polars>=1.33.0",
    "requests>=2.32.5",
    "selenium>=4.35.0",
]
